/*
 * Copyright (c) 2016 Redlink GmbH.
 */
package io.redlink.solrlib.embedded;

import com.google.common.base.Preconditions;
import io.redlink.solrlib.SolrCoreContainer;
import io.redlink.solrlib.SolrCoreDescriptor;
import io.redlink.utils.PathUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.solr.client.solrj.SolrClient;
import org.apache.solr.client.solrj.embedded.EmbeddedSolrServer;
import org.apache.solr.core.CoreContainer;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Date;
import java.util.Objects;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.ExecutorService;

/**
 * SolrCoreContainer
 */
public class EmbeddedCoreContainer extends SolrCoreContainer {

    private CoreContainer coreContainer = null;
    private Path solrHome = null;
    private boolean deleteOnShutdown;

    public EmbeddedCoreContainer(Set<SolrCoreDescriptor> coreDescriptors,
                                 EmbeddedCoreContainerConfiguration configuration) {
        this(coreDescriptors, configuration, null);
    }

    public EmbeddedCoreContainer(Set<SolrCoreDescriptor> coreDescriptors,
                                 EmbeddedCoreContainerConfiguration configuration,
                                 ExecutorService executorService) {
        super(coreDescriptors, executorService);
        Preconditions.checkArgument(configuration.getHome() != null, "solr-home not set!");
        deleteOnShutdown = configuration.isDeleteOnShutdown();
        solrHome = configuration.getHome();
    }

    @Override
    protected void init() throws IOException {
        Preconditions.checkState(Objects.isNull(coreContainer), "Already initialized!");

        if (solrHome == null) {
            solrHome = Files.createTempDirectory("solr-home");
            log.debug("No solr-home set, using temp directory {}", solrHome);
            deleteOnShutdown = true;
        }

        final Path solrHome = this.solrHome.toAbsolutePath();
        final Path lib = solrHome.resolve("lib");
        Files.createDirectories(solrHome);
        Files.createDirectories(lib);

        final Path solrXml = solrHome.resolve("solr.xml");
        if (!Files.exists(solrXml)) {
            log.info("no solr.xml found, creating new at {}", solrXml);
            try (PrintStream writer = new PrintStream(Files.newOutputStream(solrXml, StandardOpenOption.CREATE))) {
                writer.printf("<!-- Generated by %s on %tF %<tT -->%n", getClass().getSimpleName(), new Date());
                writer.println("<solr>");
                writer.printf("  <str name=\"%s\">%s</str>%n", "sharedLib", solrHome.relativize(lib));
                writer.println("</solr>");
            }
        }

        for (SolrCoreDescriptor coreDescriptor : coreDescriptors) {
            final String coreName = coreDescriptor.getCoreName();
            if (availableCores.contains(coreName)) {
                log.warn("CoreName-Clash: {} already initialized. Skipping {}", coreName, coreDescriptor.getClass());
                continue;
            }
            final Path coreDir = solrHome.resolve(coreName);
            Files.createDirectories(coreDir);
            coreDescriptor.initCoreDirectory(coreDir, lib);

            final Properties coreProperties = new Properties();
            final Path corePropertiesFile = coreDir.resolve("core.properties");
            if (Files.exists(corePropertiesFile))
                coreProperties.load(Files.newInputStream(corePropertiesFile, StandardOpenOption.CREATE));
            coreProperties.setProperty("name", coreName);
            coreProperties.store(Files.newOutputStream(corePropertiesFile), null);

            if (coreDescriptor.getNumShards() > 1 || coreDescriptor.getReplicationFactor() > 1) {
                log.warn("Deploying {} to EmbeddedCoreContainer, ignoring config of shards={},replication={}", coreName,
                        coreDescriptor.getNumShards(), coreDescriptor.getReplicationFactor());
            }

            availableCores.add(coreName);
        }

        log.info("Starting {} in solr-home '{}'", getClass().getSimpleName(), solrHome);
        coreContainer = CoreContainer.createAndLoad(solrHome, solrXml);
    }

    @Override
    public final void shutdown() throws IOException {
        Preconditions.checkState(Objects.nonNull(this.coreContainer), "Not initialized!");

        try {
            final CoreContainer cc = this.coreContainer;
            this.coreContainer = null;
            cc.shutdown();
        } catch (final Throwable t) {
            log.error("Unexpected Error during CoreContainer.shutdown(): {}", t.getMessage());
            throw t;
        }

        if (deleteOnShutdown) {
            log.debug("Cleaning up solr-home {}", solrHome);
            PathUtils.deleteRecursive(solrHome);
        }
    }

    @Override
    protected SolrClient createSolrClient(String coreName) {
        Preconditions.checkState(Objects.nonNull(coreContainer), "CoreContainer not initialized!");
        Preconditions.checkArgument(StringUtils.isNotBlank(coreName));
        return new EmbeddedSolrServer(coreContainer, coreName) {
            @Override
            public void close() throws IOException {
                // nop;
            }
        };
    }

    public CoreContainer getCoreContainer() {
        try {
            awaitInitCompletion();
            return coreContainer;
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Could not retrieve CoreContainer", e);
        }
    }
}
